package com.xtrade.android.util;

public interface EventConstant {

	int OFFSET = 100;
	
	final int TRADER_CREATE_REQUEST_CODE = OFFSET + 1;
	final int TRADER_UPDATE_REQUEST_CODE = OFFSET + 2;
	final int TRADER_PHOTO_GALLERY_REQUEST = OFFSET + 3;
	final int TRADER_PHOTO_CAMERA_REQUEST = OFFSET + 4;
	final int CONTACT_CREATE_REQUEST_CODE = OFFSET + 5;
	final int CONTACT_UPDATE_REQUEST_CODE = OFFSET + 6;
	final int CONTACT_PHOTO_GALLERY_REQUEST = OFFSET + 7;
	final int CONTACT_PHOTO_CAMERA_REQUEST = OFFSET + 8;
	
}
